# pytorch_lightning==2.0.4
seed_everything: true
trainer:
  accelerator: gpu
  strategy: ddp
  devices: 4
  num_nodes: 1
  precision: 16-mixed
  logger: null
  callbacks:
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        monitor: val_loss
        dirpath: ./checkpoints/
    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        monitor: val_loss
    - class_path: callbacks.MyPrintingCallback
  fast_dev_run: false
  max_epochs: 1
  min_epochs: 1
  profiler: simple
model:
  model_name: resnet18
  weights: ResNet18_Weights.IMAGENET1K_V1
  learning_rate: 0.01
data:
  root_dir: /data/datasets/ImageNet-1K/raw/ImageNet-1K
  batch_size: 32
  num_workers: 4
ckpt_path: null
