model:
  name: resnet18
  pretrained: false

dataset:
  data_root: /data/datasets/ImageNet-1K/raw/ImageNet-1K/

training:
  output_dir: outputs
  seed: 42
  bf16: true
  max_grad_norm: 1.0
  learning_rate: 0.1
  train_batch_size_per_device: 64
  eval_batch_size_per_device: 64
  grad_accumulation_batches: 4
  weight_decay: 1e-4
  momentum: 0.9
  num_train_epochs: 90
  logging_steps: 30
  eval_steps: 200
  save_steps: 500
  save_safetensors: true
  dataloader_num_workers: 4
  dataloader_pin_memory: true
  resume_from_checkpoint: outputs/checkpoints